### ISSUE TITLE
EACCESS on server

### ISSUE THREAD

**Issue by dkaoster** [matfin/meteor-contentful#3]
When deploying to a server with mup, I'm getting:

```
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
```

and if I comment out this line, it works.

```
MeteorContentful.listen();
```

**Comment by matfin** [comment]
Hi Daniel,

It looks like there is an issue accessing whichever port was set up as the listener. Which port number did you specify in your settings.json file for Contentful ? 

You should have something like the following, where I have set my port to 6543.

```
"contentful": {
        "accessToken": "<snip>",
        "space": "<snip>",
        "host": "cdn.contentful.com",
        "callbackToken": "<snip>",
        "callbackPort": 6543,
        "limit": 200
    },
```

Could you provide details of which platform/os you are using ?

**Comment by dkaoster** [comment]
I am using the following settings which seems to work on my local instance of meteor, error shows up when I deploy with mup (possibly because mup uses an unprivileged user account to run meteor?):

```
  "contentful": {
    "accessToken": "...",
    "space": "...",
    "host": "cdn.contentful.com",
    "limit": 100,
    "callbackToken": "...",
    "callbackPort": 4567
  }
```

Local OS is OSX yosemite, server is Ubuntu 14.14 on Digital Ocean.

**Comment by matfin** [comment]
Yep that would be true, but normally non privileged users cannot bind to ports below 1024 so I would gather that binding to 4567 should be ok.

Having said that, I will have to do some more digging (I don't use MUP) and see how to get past the problem of binding that port.

**Comment by matfin** [comment]
Hi Daniel,

Would I be able to see your nginx.conf settings as well ?

**Comment by dkaoster** [comment]
I've tried other ports too with no luck.

I'm actually not using nginx on my server at this point, just telling meteor up to load meteor directly to port 80. Is nginx required for this to work?

**Comment by matfin** [comment]
Hi Daniel,

Strictly speaking, using nginx is not required but it's good practice and can be useful if you want to use features such as load balancing, mapping other ports etc. 

I am still digging around the problem to see can I create it on a Vagrant VM. I think it's definitely an environment issue. 

Are you familiar with Vagrant at all ? I use it to try to pinpoint issues I am having on production, by spinning up an Ubuntu 14.04 vm on my development machine (OS X Yosemite).

**Comment by dkaoster** [comment]
Matt,

Makes sense. I haven't yet gotten around to putting nginx on my staging server, but will probably do so today to see if that helps.

Yes I have used vagrant before, it's a great tool for testing environments. I'll look into it more and see if I can pinpoint the exact issue.

Thanks for your help!

**Comment by matfin** [comment]
Hi Daniel,

Here is a sample nginx config file that I use when deploying sites - should be helpful for you. You will need to run the following commands to install nginx:

```
ubuntu:you$ sudo apt-get update
ubuntu:you$ sudo apt-get install nginx 
```

Copy this file with your adjustments to the directory /etc/nginx/sites-available

```
server_tokens off;

map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
}

# Maps <anything>.website.local to just website.local
server {
        server_name *.website.local;
        rewrite ^(.*) http://website.local permanent;
}

# This maps your meteor port (2000 in this case) to port 80
server {
        listen 80;

        server_name     website.local;

        location / {
                proxy_pass http://127.0.0.1:2000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header X-Forwarded-For $remote_addr;
        }
}

# This maps to my Contentful listener so I can set up my hooks there nicely
server {
        listen 80;
        server_name     app.website.local;
        location / {
                proxy_pass http://127.0.0.1:6789;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header X-Forwarded-For $remote_addr;
        }
}

# This is to use nginx to serve static media from a root directory
# Do not let nodejs or meteor handle this, it can slow things down 
# horribly especially for heavier assets 
server {
        listen 80;
        server_name media.website.local;
        root /home/website/media/processed;
}
```

Once copied, link the file to sites-available which will make it active, then test it and if it comes back with no errors, reload nginx

```
ubuntu:you$ sudo ln -s /etc/sites-available/<your-nginx-conf-file> ../sites-enabled/<your-nginx-conf-file>
ubuntu:you$ sudo nginx -t 
ubuntu:you$ sudo nginx -s reload
```

Let me know if you have any problems.

**Comment by dkaoster** [comment]
After I setup nginx, it appears to work! I wonder why that was the case... Maybe put something into the readme about nginx?

Thanks for all of your help.

**Comment by matfin** [comment]
Hi Daniel, 

Glad you got it working. Will continue investigating and document what happened here. Glad you got it working in the end, but its always good to follow up when something 'just works' without explanation.

**Comment by Jehu** [comment]
same problem here if app run without nginx as node server only.

so i installed and configured nginx. But if i use your mentioned nginx-config, the Webhook url http://app.mydomain.com gets an 404 "Cannot POST /"

any suggestions?

**Comment by matfin** [comment]
Hi Jehu,

Can you try POSTing to http://app.mydomain.com/hooks/contentful ?

**Comment by Jehu** [comment]
sorry, "mup deploy" is not working at the moment if i try to use MeteorContentful.
I have to remove it to get the app working on live server again (digitalocean).

have to try later again. will come back to this topic.

**Comment by matfin** [comment]
Hi Jehu,

Can you paste any error messages you are getting (or is it still the same EACCESS message)?
