### ISSUE TITLE
publications and subscriptions can't be renamed?

### ISSUE THREAD

**Issue by Jehu** [matfin/meteor-contentful#4]
Clientside collections are empty if i change the publish/subscribe name change from "entries" to another String.

This is working:
my `server/publish.js`:

```
  MeteorContentful.start().fetch('contentTypes').fetch('entries').fetch('assets');
  Meteor.publish('entries', function () {
    var cType = Collections.contentTypes.findOne({name: "news"});
    return Collections.entries.find({"sys.contentType.sys.id": cType.sys.id});
  });
```

my `client/subscribe.js`:

```
  news_collection = new Mongo.Collection('entries');
  Meteor.subscribe('entries');
```

But if i change the names from "entries" to "news" it is broken:
this sould be my `server/publish.js`:

```
  MeteorContentful.start().fetch('contentTypes').fetch('entries').fetch('assets');
  Meteor.publish('news', function () {
    var cType = Collections.contentTypes.findOne({name: "news"});
    return Collections.entries.find({"sys.contentType.sys.id": cType.sys.id});
  });
```

this sould be my `client/subscribe.js`:

```
  news_collection = new Mongo.Collection('news');
  Meteor.subscribe('news');
```

It would be nice to have a subscription for each content type. that's the reason for my question. :-)

**Comment by matfin** [comment]
Hi,

I also had this issue before and came up with a solution. If you look at this file in a meteor website I launched recently, it explores publications and subscriptions with different names.

https://github.com/matfin/annachristoffer/blob/master/server/publications.es6.js

You could take a look at this as a guide. I will go into this in more detail soon.

**Comment by matfin** [comment]
Just to elaborate further on the above, here is what I did to have a collection for each of my content types. 

Firstly, I created a client side collection for each content type as follows. An example of this in practice can be seen [here](https://github.com/matfin/annachristoffer/blob/master/packages/core/_src/core.es6.js).

```
let projects =  new Mongo.Collection('projects');
let categories = new Mongo.Collection('categories');
let pages = new Mongo.Collection('pages');
```

After that, I set up my publish functions on the server side as follows, and you can see a practical example of this [here](https://github.com/matfin/annachristoffer/blob/master/server/publications.es6.js).

```
Meteor.publish('projects', function(filter) {
    entriesOfType.call(this, 'projects', filter);
});

Meteor.publish('categories', function(filter) {
    entriesOfType.call(this, 'categories', filter);
});

Meteor.publish('pages', function(filter) {
    entriesOfType.call(this, 'pages', filter);
});
```

Notice the entriesOfType function that is called in each publish function. What this does it take in the content type name as a parameter, and uses this to find the content type inside a collection I had set up. If I can find the content type id from the name, I can use that to filter the entire entries collection to only fetch entries that match the correct content type id.

The rest of the function allows me to fire the added() callback function so I can sync the collections from server to client without having to declare the collection explicitly by name on the server. This makes the code much cleaner. 

Finally, what I am able to do is make a call to subscribe to the entries collection by specifying the content type name inside the client side templates (I make the call in the subscribed callback). This means I only get the entries that I am interested in for a particular view, filtered by the content type name. 

```
/**
 *  Template.views_list
 *  Callback function called automatically when the template has been created
 *
 *  @method created
 */
Template.views_list.onCreated(function() {
    this.subscribe('projects');
});
```

You can see the code for the template [here](https://github.com/matfin/annachristoffer/blob/master/client/controllers/views/list.es6.js).

I hope this helps and if you have any more questions please let me know.

**Comment by Jehu** [comment]
Thanks, i will  try this approach as soon as i can use the plugin on live again.
