### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by steinitz-zz** [matfin/meteor-contentful#5]
Thanks for sharing your contentful package.  Nice piece of engineering.
Using your helpful instructions I was able to get it up and running easily .

Testing it with Contentful's default entries for a new 'space' in Meteor 1.2, updateToCollection successfully loads the content-type entries and the assets but returns an error, "Maximum call stack size exceeded", when loading the more-elaborate 'post' entries, e.g. 'Seven tips From Earnest Hemingway...'

I hope this report is useful.

**Comment by matfin** [comment]
Hi Steve,

Thanks for the report. Would it be possible to paste what the logged output is? Could you also provide information on your server set up?

Matt

**Comment by steinitz-zz** [comment]
Hi Matt,

Thanks for your reply.

Oops.  In the end, having run out of time, I deleted the problem entries from contentful and created a new content type which never fails - so I can't easily reproduce the problem right now.  The full error message, from Collection.insert, was "Maximum call stack size exceeded" followed by the stack, I believe.  

My 'server' is a MacBook, for now.  I hadn't considered that that might be a factor.

I take it from your reply that you are not able to reproduce the problem with a fresh contentful space.

Let me catch up on my work and maybe I'll be able to make time to set up new space and reproduce the error for you.

Thanks again,

Steve

**Comment by matfin** [comment]
Hi Steve,

The next time this comes up can you paste snippets containing sample JSON of your content types along with a snapshot of the error you are getting - this will give me a better indication of where things are going wrong. I will close this for now but feel free to reopen it if the problem persists.

Thanks,

Matt
