### ISSUE TITLE
Webhook inconsistent with GET

### ISSUE THREAD

**Issue by steinitz-zz** [matfin/meteor-contentful#7]
Hi Matt,

Contentful have just confirmed that the webhook sends less info than a GET (fetch).  Specifically, the webhook media object fields don't, themselves, have a 'fields' entry, just a 'sys'.  So, for example, I'll need to fetch image urls from Contentful after the webhook has fired -- at least two minutes later according to Mark Douglas at Contentful support.

So, I'd like to ask you if I'm missing something regarding the package, and/or, how have you worked around this?

Cheers,

Steve

**Comment by matfin** [comment]
Hey Steve,

I did see that the content being pushed to the webhook was slightly different from what was seen during fetching using a GET request, but the data that came through also included fields along with sys.

I had to write a [remapping function](https://github.com/matfin/meteor-contentful/blob/master/_src/meteor_contentful.js#L92) to normalise the data and make it ready to be added to the collection. When it came to fetching uploaded images, they were usually available immediately. When the [images collection is updated](https://github.com/matfin/meteor-contentful/blob/master/_src/image_processor.js#L198), it should grab the url for the image, fetch it and then start transforming it. I do this using Meteors observe function which is run when a collection is updated.

Would it be possible for you to show me what comes through after data is pushed to the webhook, and some information on what the contentType looks like? Could you also paste what your settings file looks like with sensitive data omitted?

Thanks,

Matt

**Comment by steinitz-zz** [comment]
Hi Matt,

I worked around this last week.  Fortunately, the assets remain in the database so I can load them as needed.

I saw your remapping function.  Nice work.  I might have time later to figure out why it's not 'fleshing out' the images in my entries collection.  Per your request to see what the data looks like before and after the webhook here is an excerpt (sorry about the length of it):

When fetched at startup:

```
{
  "_id": "mSW9WeuhfRy5uTYQE",
  "sys．id": "631mxQpBFSg2AAsQSSooAG",
  "fetchedAt": 1448842286652.0,
  "sys": {
    "id": "631mxQpBFSg2AAsQSSooAG",
    "revision": 4,
    "type": "Entry",
    "locale": "en-US",
    "space": {
      "sys": {
        "id": "mavaz8ode94n",
        "revision": null,
        "type": "Link",
        "locale": null,
        "space": null,
        "contentType": null,
        "createdAt": null,
        "updatedAt": null
      }
    },
    "contentType": {
      "sys": {
        "id": "5t5jelHve8QMMyY0w20qWA",
        "revision": null,
        "type": "Link",
        "locale": null,
        "space": null,
        "contentType": null,
        "createdAt": null,
        "updatedAt": null
      }
    },
    "createdAt": new Date(1447894792975),
    "updatedAt": new Date(1448581311704)
  },
  "fields": {
    "heroImage": null,
    "title": "Youtube Test",
    "body": "Lorem ipsum ...,",
    "quote": "Quisque rutrum...ured": false,
    "heroImageGallery": [
      {
        "sys": {
          "id": "3VUqINOPbWyeCcoiioMQ4g",
          "revision": 1,
          "type": "Asset",
          "locale": "en-US",
          "space": {
            "sys": {
              "id": "mavaz8ode94n",
              "revision": null,
              "type": "Link",
              "locale": null,
              "space": null,
              "contentType": null,
              "createdAt": null,
              "updatedAt": null
            }
          },
          "contentType": null,
          "createdAt": new Date(1448578794061),
          "updatedAt": new Date(1448578794061)
        },
        "fields": {
          "file": {
            "fileName": "Screen Shot 2015-11-27 at 9.54.02 am.png",
            "contentType": "image/png",
            "details": {
              "image": {
                "width": 815,
                "height": 500
              },
              "size": 197293
            },
            "url": "//images.contentful.com/mavaz8ode94n/3VUqINOPbWyeCcoiioMQ4g/56763451cf2b0ba047512c906cc8d20f/Screen_Shot_2015-11-27_at_9.54.02_am.png"
          },
          "title": "Dance Main Image",
          "description": "Dance Main Image"
        }
      }
    ]
  },
  "refreshedAt": 1448842958805.0
}
```

Here is the same document after a webhook - you can see that the image lacks 'fields' attributes:

```
{
  "_id": "p2spPpqEZzxaA6nmk",
  "sys．id": "631mxQpBFSg2AAsQSSooAG",
  "fetchedAt": 1448844619250.0,
  "refreshedAt": 1448844619250.0,
  "fields": {
    "heroImage": null,
    "title": "Youtube Test",
    "body": "Lorem ipsum ...,",
    "quote": "Quisque rutrum...,",
    "youtubeUrl": "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/r1rmktHvvs0\" frameborder=\"0\" allowfullscreen></iframe>",
    "featured": false,
    "heroImageGallery": [
      {
        "sys": {
          "type": "Link",
          "linkType": "Asset",
          "id": "3VUqINOPbWyeCcoiioMQ4g"
        }
      }
    ]
  },
  "sys": {
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "mavaz8ode94n"
      }
    },
    "type": "Entry",
    "contentType": {
      "sys": {
        "type": "Link",
        "linkType": "ContentType",
        "id": "5t5jelHve8QMMyY0w20qWA"
      }
    },
    "id": "631mxQpBFSg2AAsQSSooAG",
    "revision": 5,
    "createdAt": "2015-11-19T00:59:52.975Z",
    "updatedAt": "2015-11-30T00:50:18.909Z"
  }
}
```

Per your request, here is our settings file for development:

```
{
    "public": {

    },
    "contentful": {
        "accessToken": "<snip>",
        "space": "<snip>",
        "host": "cdn.contentful.com",
        "callbackToken": "xyz",
        "callbackPort": <snip>,
        "limit": 50
    }
}
```

Note that our server administrator was unable to open a port on the elastic-beanstalk-continuous-integration extravaganza, so, we adapted your listener to be an action on an iron-router route.  It all happens on port 80 now.  I can show you how we did it if you are interested, perhaps in another thread to avoid cluttering this one.

Thanks again for following up.

**Comment by matfin** [comment]
Hi Steve. 

I will look into this. When pasting your settings, make sure not to include any sensitive data like access tokens or space ids. I've edited the above to remove them.

Matt
