### ISSUE TITLE
Support for Locales ?

### ISSUE THREAD

**Issue by origindesign** [matfin/meteor-contentful#8]
I'm just testing your package and it does seem pretty handy. As of now it seems to only pull data from the default language and store them in the DB. It doesn't seem to insert any other locales data. I was just wondering if there is any support for that ? Or if there is a plan for this in the future.

**Comment by matfin** [comment]
Hi,

Unfortunately, at the moment there is no support for locales. I would love to be able to add it (I could certainly use it myself), but given this is a feature only for users with pro accounts, I won't be able to add support without one of those. 

I will get in touch with Contentful and if they would be willing to cooperate, I could build this feature in without too much difficulty, but without their input, it would be almost impossible. 

Matt
